is_train: True 
out_root_path: /outputs/audio2pose/ 
train_data_path: /datasets/beat_cache/beat_4english_15_141/train/ 
val_data_path: /datasets/beat_cache/beat_4english_15_141/val/ 
test_data_path: /datasets/beat_cache/beat_4english_15_141/test/ 
mean_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
std_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
torch_hub_path: /datasets/hub/checkpoints/ 
e_path:  /datasets/beat_cache/beat_4english_15_141/weights/ges_axis_angle_300.bin #ae_300_axisangle_2_rec_val.bin #ges_axis_angle_300.bin #ae_300_rot6d_2468_rec_val_v3.bin # # .../ae_18f.bin
test_ckpt: /datasets/beat_cache/beat_4english_15_141/weights/6d_2468_574.bin #6d_2468_574.bin #.../camn.bin
dataset: beat
new_cache: True
head_rep: head_rot
audio_rep: wave16k
facial_rep: facial52
speaker_id: id
pose_rep: bvh_axis_angle #bvh_rot_6d #bvh_axis_angle
pose_file_extension: axisangle #6d #axisangle
# chenge eval rotation rep between rot6d or axis-angle
eval_rotation: AXIS_ANGLE #AXIS_ANGLE #ROT_6D
pose_eval_rep: bvh_axis_angle #bvh_axis_angle #bvh_rot_6d
eval_joint_dims: 3 #3 #6
#word_rep: text
sem_rep: sem # SRGR requires this
emo_rep: emo
freeze_wordembed: True
speaker_dims: 30
facial_dims: 51
#pose_dims: 141
output_joint_dims: 3 #euler angles
train_joint_dims: 3 #axis-angle
word_f: 0 #128 # Realtime test
emotion_f: 0 #8 # Realtime test
speaker_f: 8
audio_f: 128 #128
facial_f: 32 #32
head_rot_f: 0 #12
word_index_num: 5793
word_dims: 300
lr_base: 0.00025
batch_size: 256
no_adv_epoch: 10 #200
hidden_size: 256
model: iorgesture
g_name: CaMN
d_name: ConvDiscriminator
eval_model: motion_autoencoder
e_name: HalfEmbeddingNet
vae_length: 300
rec_weight: 500
adv_weight: 0.1
trainer: iorgesture
kld_weight: 0.0
div_reg_weight: 0.0
grad_norm: 200
epochs: 800
test_period: 25

srgr_threshold: 0.5