is_train: True 
out_root_path: /outputs/audio2pose/ 
train_data_path: /datasets/beat_cache/beat_4english_15_141/train/ 
val_data_path: /datasets/beat_cache/beat_4english_15_141/val/ 
test_data_path: /datasets/beat_cache/beat_4english_15_141/test/ 
mean_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
std_pose_path: /datasets/beat_cache/beat_4english_15_141/train/
torch_hub_path: /datasets/hub/checkpoints/ 
e_path:  /datasets/beat_cache/beat_4english_15_141/weights/ae_topology_spk2_rec_val_399.bin #ae_300_axisangle_2_rec_val.bin #ges_axis_angle_300.bin #ae_300_rot6d_2468_rec_val_v3.bin # # .../ae_18f.bin
test_ckpt: /datasets/beat_cache/beat_4english_15_141/weights/6d_spk2468_wo_head_last_474.bin #6d_2468_574.bin #.../camn.bin
dataset: beat

new_cache: False
cache_path: score_spk2

#word_rep: text
head_rep: head_rot
audio_rep: wave16k
facial_rep: facial52
speaker_id: id
pose_rep: bvh_rot_6d #bvh_rot_6d #bvh_axis_angle
pose_file_extension: 6d #6d #axisangle
# chenge eval rotation rep between rot6d or axis-angle
eval_rotation: ROT_6D #AXIS_ANGLE #ROT_6D
pose_eval_rep: bvh_rot_6d #bvh_axis_angle #bvh_rot_6d
eval_joint_dims: 6 #3 #6
sem_rep: sem # SRGR requires this
emo_rep: emo
freeze_wordembed: True
speaker_dims: 30
facial_dims: 51
#pose_dims: 141
output_joint_dims: 3 #euler angles
train_joint_dims: 6 #axis-angle / 6d
word_f: 0 #128
emotion_f: 0 #8
speaker_f: 8
audio_f: 128 #128
facial_f: 32 #32
head_rot_f: 0 #12
word_index_num: 5793
word_dims: 300
lr_base: 0.00025
batch_size: 256
no_adv_epoch: 0 #200
hidden_size: 256
model: iorgesture #iorgesture #camn
g_name: CaMN
d_name: ConvDiscriminator
eval_model: motion_autoencoder
e_name: VAESKConv #VAESKConv #VAEConvMLP #HalfEmbeddingNet
vae_length: 216 #300
rec_weight: 500
adv_weight: 0.1
trainer: iorgesture #iorgesture #camn
kld_weight: 0.0
div_reg_weight: 0.0
grad_norm: 200
epochs: 800
test_period: 25

srgr_threshold: 0.5